### ISSUE TITLE
AddressParse.pm line 567: Use of uninitialized value $curr_value in uc

### ISSUE THREAD

**Issue by wdbaker54** [kimryan/Lingua-EN-AddressParse#1]
In version 1.26 I am getting several of these errors and I am able to remove them by changing line 563 from:
`my $curr_value = $orig_components{$curr_key}`
to
`my $curr_value = $orig_components{$curr_key} || '';`
It seems that the $orig_components{'base_street_name'} is being changed along the way from blank to undef (in a specific case - the error may be generated from one of the other values but I am too lazy to see if all of my errors are being generated from the same field being undefined).

**Comment by kimryan** [comment]
Thanks, can you supply a sample address that causes this error?

**Comment by wdbaker54** [comment]
Here is a slightly modified (for security sake) version of one that causes the error:
`123 Summitridge, Beverly Hills, CA 90210`

**Comment by kimryan** [comment]
This address won't parse for me as it has no street type, such as Road or Street. But I don't get any errors. What version of Perl are you using?

**Comment by kimryan** [comment]
OK, I've added your suggestion to the next version (unreleased)  and fixed up the way base_street_name is determined. Can send you the new version if you want to test it.

**Comment by wdbaker54** [comment]
Could the problem be that I am religious about using strict and warnings? The version of perl is 5.22.1. I understand that the address is not parse-able - my only concern was that the error message was messing up my logs. Thanks for your quick response and I would be glad to test the new version when it comes out.

**Comment by kimryan** [comment]
OK, I can reproduce your warnings now. Have attached new version that fixes this for me. Maybe check it out at your end?
[AddressParse.zip](https://github.com/kimryan/Lingua-EN-AddressParse/files/1602427/AddressParse.zip)

**Comment by wdbaker54** [comment]
I have been testing your new version all morning on our database of 200K addresses and I haven't found any new warnings and the warning I mentioned has not come up. Thanks for the fix.

**Comment by kimryan** [comment]
Great. Version 1.27 has now been committed. Would be interested to know how you found this module, and if you have compared it to others. The way Perl and CPAN name spaces are set up makes it hard for people to find this on Git it seems.

**Comment by wdbaker54** [comment]
I have been using [Lingua::EN::AddressParse](http://search.cpan.org/~kimryan/Lingua-EN-AddressParse-1.27/) since at least 2009 (I had to check our database for the earliest record of use - it could have been earlier but that was the oldest record). I was tasked to try and check for duplicate postal addresses and, since everything we done back then was perl, did a bunch of searches on CPAN. I found Lingua and also [Geo::StreetAddress::US](http://search.cpan.org/~timb/Geo-StreetAddress-US-1.04/US.pm) and decided to team them up by using your library first followed by Geo as a fallback and having a final fallback of a simple set of address clean-ups before calculating an MD5 checksum. It seemed yours passes 75% of the time and Geo catches another 20%. BTW - we have now migrated to PHP for most of our tools but I have been unable to locate anything that comes close to Lingua to doing the job of parsing addresses - so I still use an external call to a perl app to do the job. Great work!

**Comment by kimryan** [comment]
Thanks, glad the module is useful for you. (If you like you could star it, I would appreciate that) I've seen may ports of Geo:;StreetAddress::US to other languages, a lot of them not updated. Everyone seems to use Github now for open source code. But I feel CPAN is much better organised, with module doco requirements, testing, controlled name spaces etc. Seems like we've gone backwards. I found PHP a backward step from Perl also. GoogleMaps API is also useful for parsing addresses, but you have to pay for each parse.
